### ISSUE TITLE
Can you add the windows binaries of libvpx library to repo

### ISSUE THREAD

**Issue by ex** [sigint9/shadercap#1]
Hello, I'm having lots of trouble recompiling the visual studio libs of libvpx, maybe is something with my current system, so I want to know if you can add the libraries to the repo to rebuild the project, I want to quit thelimit of 99 seconds of exportation. thanks!

**Comment by sigint9** [comment]
Hi, I removed this GUI limitation and rebuilt it for Windows. I'm calling it version 1.2, and you can get it from the new github pages site http://sigint9.github.io/shadercap/ I hope this fixes your issue!

**Comment by ex** [comment]
Thank you very much. 
Still I need to find a way to recompile the program but is not that urgent now :D
